### PR TITLE
Added account editing. Fixed account image path

### LINKED ISSUE #13: View and edit your account information

### PR DESCRIPTION
**Pull request by cpreisinger**
Closes #13 

- [x] README is up to date
- [x] Docs are up to date with changes (modules and functions)
- [x] Tests are included for changes
- [ ] ~~Links in emails use the `_url` route helpers~~

### CODE REVIEW

File: lib/idea_portal/accounts.ex [hunk 1]
```diff
@@ -37,6 +37,27 @@ defmodule IdeaPortal.Accounts do
     end
   end
 
+  @doc """
+  Changeset for account editing
+  """
+  def edit(user), do: User.edit_changeset(user, %{})
```
Comment (oestrich) [inline lib/idea_portal/accounts.ex]: This can run through the same changeset as the edit function below. We aren't saving anything from it, so resetting the email tokens is fine to pass through (also it shouldn't trigger as no email was passed in)

File: lib/web/controllers/account_controller.ex [hunk 2]
```diff
@@ -0,0 +1,32 @@
+defmodule Web.AccountController do
+  use Web, :controller
+
+  alias IdeaPortal.Accounts
+
+  def edit(conn, _params) do
+    user = conn.assigns.current_user
```
Comment (oestrich) [inline lib/web/controllers/account_controller.ex]: If only for keeping style with the other controllers:

```
%{current_user: user} = conn.assigns
```
